Doku Anpassung
europace/baufi-passende-vorschlaege-api pull request #118
Opened 2022-07-14 11:18 UTC by EPRonnyS

2022-07-14 12:13 UTC, damyan-h commented on README.md
> +Finanzierungsvorschlag gemerkt werden. Sollte der FInanzierungvorschlag schon vorher gebookmarked worden sein, ist die `anfrageId` optional.
```suggestion
Finanzierungsvorschlag gebookmarked werden. Sollte der Finanzierungvorschlag schon vorher gebookmarked worden sein, ist die `anfrageId` optional.
```

2022-07-15 08:49 UTC, rene-hae requested changes

2022-07-15 08:49 UTC, rene-hae commented on README.md
> +Um zu sehen welche Finanzierungsvorschläge man gebookmarked oder aktzepiert hat, kann man list verwenden.
> aktzepiert
Bitte in diesem Satz berichtigen: akzeptiert

2022-07-15 08:49 UTC, rene-hae commented on README.md
> +Wurde bereits ein Finanzierungsvorschlag akzeptiert, wird jeder weitere Finanzierungsvorschlag ignoriert.
Sollte dieser Satz wegen dem _delete_ aktualisiert werden?
Bsp.:
Ein akzeptierter Finanzierungsvorschlag kann mit _delete_ gelöscht werden. So könnte ein anderer Finanzierungsvorschlag akzeptiert werden.

2022-07-15 08:49 UTC, rene-hae commented on README.md
> +Finanzierungsvorschlag akzeptiert werden. Sollte der Finanzierungvorschlag schon vorher gebookmarked worden sein, ist die `anfrageId` optional.
> Finanzierungvorschlag

Bitte berichtigen : Finanzierungsvorschlag

Vorschlag: was hältst Du von diesem Satz?
_Sollte der Finanzierungsvorschlag bereits gebookmarked sein, ist die `anfrageId`optional._

2022-07-15 08:49 UTC, rene-hae commented on README.md
> +Zum Löschen von gebookmarkten oder akzepierten Finanzierungsvorschlägen.
> akzepierten

Bitte berichtigen:
_akzeptierten_

2022-07-18 09:12 UTC, merged